### ISSUE TITLE
Cannot pass the url in golang sdk

### ISSUE THREAD

**Issue by sskmy1024y** [kenakamu/LINESimulator#9]
Currently, `line-bot-sdk-go` constructor cannot have a basepoint with string.

https://github.com/line/line-bot-sdk-go/blob/de8cb19605d2e5107a68b1620117b617502f6061/linebot/client.go#L73-L80

If you want to fix it, you would write it like this:
```go
bot, err := linebot.New(
		channelSecret,
		channelToken,
		linebot.WithEndpointBase("http://localhost:8080"),
	)
```

However, even with this modification, a reply is not sent due to the following error.
`linebot: APIError 404 Not Found`
Also, the destination is as follows: 
`http://localhost:8080/v2/bot/message/reply`

Maybe it doesn't support the latest SDK, can it be fixed?

Thank you !

**Comment by kenakamu** [comment]
This is more like golang SDK side of the issue.
